const MOVE_CITIES = [
 {city:"Lagos",country:"Nigeria",currency:"NGN",emoji:"🌴",rent:350000,food:126000,transport:27000,coffee:36000,color:"green"},
 {city:"Dubai",country:"UAE",currency:"AED",emoji:"🌇",rent:5000,food:1560,transport:270,coffee:480,color:"cyan"},
 {city:"London",country:"United Kingdom",currency:"GBP",emoji:"🎡",rent:1800,food:570,transport:185,coffee:84,color:"violet"},
 {city:"Tokyo",country:"Japan",currency:"JPY",emoji:"🗼",rent:145000,food:43500,transport:6600,coffee:11600,color:"pink"},
 {city:"New York",country:"United States",currency:"USD",emoji:"🗽",rent:2600,food:660,transport:127,coffee:114,color:"blue"},
 {city:"Cape Town",country:"South Africa",currency:"ZAR",emoji:"⛰",rent:11000,food:5700,transport:780,coffee:840,color:"gold"}
];
const MOVE_CURRENCIES=["USD","NGN","GBP","EUR","AED","JPY","ZAR","CAD","AUD","CNY","INR"];
const MOVE_LIFESTYLES={lean:{label:"Lean explorer",factor:.66},balanced:{label:"Balanced life",factor:1},luxury:{label:"Luxury mode",factor:1.72}};
function moveFormat(n,c){return new Intl.NumberFormat("en",{style:"currency",currency:c,maximumFractionDigits:0}).format(n)}
function populateMove(){const select=document.getElementById("moveCurrency"), preferred=JSON.parse(sessionStorage.getItem("currensee_session")||"{}").defaultCurrency||"USD";select.innerHTML=MOVE_CURRENCIES.map(c=>`<option ${c===preferred?"selected":""}>${c}</option>`).join("")}
function moveCard(r,max){const {city,emoji,country,currency,color}=r.profile, days=Math.max(1,Math.floor(r.days)), width=Math.max(8,Math.min(100,r.days/max*100));return `<article class="move-race-card move-${color}"><div class="move-race-city"><span>${emoji}</span><div><small>${country}</small><h3>${city}</h3></div><b>${days} days</b></div><div class="move-track"><span style="--runway:${width}%"></span></div><div class="move-race-details"><span>Monthly life <strong>${moveFormat(r.monthly,currency)}</strong></span><span>Housing <strong>${Math.round(r.rentShare)}%</strong></span><span>Daily burn <strong>${moveFormat(r.monthly/30,currency)}</strong></span></div></article>`}
async function launchMove(){const amount=Number(document.getElementById("moveAmount").value), source=document.getElementById("moveCurrency").value, life=MOVE_LIFESTYLES[document.getElementById("moveLifestyle").value], status=document.getElementById("moveStatus"), btn=document.getElementById("moveLaunch");if(!amount||amount<=0){status.textContent="Enter a budget greater than zero.";return}btn.disabled=true;btn.classList.add("lens-launching");status.textContent="Converting your budget and starting six life runways…";try{const results=await Promise.all(MOVE_CITIES.map(async profile=>{const q=source===profile.currency?{conversion_result:amount}:await convertCurrencyPair(source,profile.currency,amount);const monthly=(profile.rent+profile.food+profile.transport+profile.coffee)*life.factor;return {profile,monthly,days:q.conversion_result/(monthly/30),rentShare:profile.rent*life.factor/monthly*100}}));results.sort((a,b)=>b.days-a.days);const max=results[0].days;document.getElementById("moveRace").innerHTML=results.map(r=>moveCard(r,max)).join("");const best=results[0];document.getElementById("moveResultTitle").textContent=`${moveFormat(amount,source)} becomes a different life in every city.`;document.getElementById("moveResultMeta").textContent=`${life.label} · live conversion snapshot`;document.getElementById("moveWinnerTitle").textContent=`${best.profile.city} gives your budget its longest runway.`;document.getElementById("moveWinnerText").innerHTML=`At a <strong>${life.label.toLowerCase()}</strong> pace, ${moveFormat(amount,source)} lasts approximately <strong>${Math.floor(best.days)} days</strong> in ${best.profile.city}, with a monthly lifestyle estimate of <strong>${moveFormat(best.monthly,best.profile.currency)}</strong>.`;document.getElementById("moveWinnerBadge").innerHTML=`<span>Longest runway</span><strong>${best.profile.emoji} ${best.profile.city}</strong>`;status.textContent="Your global runway is ready. Watch where your money travels furthest."}catch{status.textContent="Live rates could not be reached. Check your connection and try again."}finally{btn.disabled=false;btn.classList.remove("lens-launching")}}
document.addEventListener("DOMContentLoaded",()=>{populateMove();document.getElementById("moveLaunch").addEventListener("click",launchMove);launchMove()});
